### ISSUE TITLE
[0.2.0] undefined symbol: zif_SDL_PointInRect

### ISSUE THREAD

**Issue by remicollet** [kea/php-sdl-mixer#2]
extension is unusable
`
Warning: PHP Startup: Unable to load dynamic library 'modules/sdl_mixer.so' (tried: modules/sdl_mixer.so (modules/sdl_mixer.so: undefined symbol: zif_SDL_PointInRect), /usr/lib64/php/modules/modules/sdl_mixer.so.so (/usr/lib64/php/modules/modules/sdl_mixer.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
`

I see the **SDL_PointInRect** function in stub.php and arginfo.h, but not in any C file.

(notice php is build with --enable-rtld-now to ensure all used symbols are property defined at load time, to avoid segfault later, when used, AFAIK this is the default in various Linux distributions)

**Comment by kea** [comment]
First release, first big error. I made the package on dirt local git repo 😓.
I've just uploaded the correct files.
What do you suggest for testing the package before release?
Copy the tgz in another dir and install/test it locally?

**Comment by remicollet** [comment]
0.3.0 is still broken

`Warning: PHP Startup: Unable to load dynamic library 'sdl_mixer.so' (tried: /home/rpmbuild/SPECS/remirepo/sdl_mixer-0.3.0/modules/sdl_mixer.so (/home/rpmbuild/SPECS/remirepo/sdl_mixer-0.3.0/modules/sdl_mixer.so: undefined symbol: zif_SDL_SetError), /home/rpmbuild/SPECS/remirepo/sdl_mixer-0.3.0/modules/sdl_mixer.so.so (/home/rpmbuild/SPECS/remirepo/sdl_mixer-0.3.0/modules/sdl_mixer.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
`

Again, SDL_SetError is in stub and arginfo, but not defined anywhere


>  What do you suggest for testing the package before release?
> Copy the tgz in another dir and install/test it locally?

Yes.
And build it again a PHP debug build, also using  --enable-rtld-now

**Comment by remicollet** [comment]
PR #3 and PR #4 allow to build and load this ext.

**Comment by kea** [comment]
Thank you, I've really appreciated your contribution.
